Fix/edx 2201
bcgov/EDUC-EDX pull request #1445
Opened 2024-03-20 23:33 UTC by keeganbcgov

2024-03-21 18:04 UTC, SodhiA1 requested changes

2024-03-21 18:25 UTC, keeganbcgov commented on backend/src/routes/schools.js
> +router.get('/schoolDetailsById/:schoolID', passport.authenticate('jwt', {session: false}, undefined), isValidBackendToken, findSchoolID_params, checkEDXUserAccessToRequestedInstitute, getFullSchoolDe
I tried to keep the logic the same from the old pattern - there wasn't previously a permission check. In this case we're checking if the current user is a user of the school or the school's district. We can definitely add a permission check, if needed, though. Maybe EDX_SCHOOL_EDIT?

2024-03-21 18:27 UTC, keeganbcgov commented on backend/src/routes/schools.js
> +router.post('/update-contact', passport.authenticate('jwt', {session: false}, undefined), isValidBackendToken, findSchoolID_body, checkEDXUserAccessToRequestedInstitute, forbidActionOnOffshoreSchools
I tried to keep the logic the same from the old pattern - there wasn't previously a permission check. In this case we're checking if the current user is a user of the school or the school's district. We can definitely add a permission check, if needed, though. Maybe EDX_SCHOOL_EDIT?

2024-03-21 18:28 UTC, keeganbcgov commented on backend/src/components/permissionUtils.js
> +async function loadSecureExchange(req, res, next) {
I did have a couple of calls with team members around this pattern before I dove into it. Definitely worth noting and requesting feedback.

2024-03-21 18:28 UTC, keeganbcgov commented on backend/src/components/permissionUtils.js
> +    return next();
I did have a couple of calls with team members around this pattern before I dove into it. Definitely worth noting and requesting feedback.

2024-03-21 18:28 UTC, keeganbcgov commented on backend/src/components/permissionUtils.js
> +      message: 'Token is unavailable.'
I did have a couple of calls with team members around this pattern before I dove into it. Definitely worth noting and requesting feedback.

2024-03-21 18:30 UTC, keeganbcgov commented on backend/src/routes/districts.js
> +router.get('/:districtID', passport.authenticate('jwt', {session: false}, undefined), isValidBackendToken, validateAccessToken, findDistrictID_params, checkEDXUserAccessToRequestedInstitute, getDistr
I tried to keep the logic the same from the old pattern - there wasn't previously a permission check. In this case we're checking if the current user is a user of the district. We can definitely add a permission check, if needed, though. Maybe EDX_DISTRICT_EDIT?

2024-03-21 18:32 UTC, keeganbcgov commented on backend/src/routes/edx.js
> +router.post('/user-activation', passport.authenticate('jwt', {session: false}, undefined), isValidBackendToken, validateAccessToken, activateEdxUser);
I tried to keep the logic the same from the old pattern - there wasn't previously a permission check. In this case, I don't think we would be able to run a permission check as they aren't a current/active EDX User at this point.

2024-03-21 18:38 UTC, keeganbcgov commented on backend/src/routes/student.js
> +router.get('/', passport.authenticate('jwt', {session: false}, undefined), isValidBackendToken, validateAccessToken, getStudentByPEN);
I tried to keep the logic the same from the old pattern - there wasn't previously a permission check. In this case we're checking if the current user is a user of the district. We can definitely add a permission check, if needed, though. Maybe SECURE_EXCHANGE? Although, maybe this endpoint will eventually be called by SDC?

2024-03-21 18:45 UTC, SodhiA1 commented on backend/src/routes/schools.js
> +router.get('/schoolDetailsById/:schoolID', passport.authenticate('jwt', {session: false}, undefined), isValidBackendToken, findSchoolID_params, checkEDXUserAccessToRequestedInstitute, getFullSchoolDe
Both schools and districts can access this data. Get by Id is also available to users with sdc access for step-4 and step-5. That would also include put/post.
The only place we don't need perm check is for code table data

2024-03-21 18:45 UTC, SodhiA1 commented on backend/src/routes/schools.js
> +router.post('/update-contact', passport.authenticate('jwt', {session: false}, undefined), isValidBackendToken, findSchoolID_body, checkEDXUserAccessToRequestedInstitute, forbidActionOnOffshoreSchools
same as above

2024-03-21 18:48 UTC, SodhiA1 commented on backend/src/routes/student.js
> +router.get('/', passport.authenticate('jwt', {session: false}, undefined), isValidBackendToken, validateAccessToken, getStudentByPEN);
I think right now SECURE_EXCHANGE is enough. We don't use it for the school sdc flow, maybe it will be needed for ministry flow later.

2024-03-25 22:39 UTC, SodhiA1 approved these changes

2024-03-25 22:39 UTC, merged